const personalQR = require('../models/personalQR');
const linkQR = require('../models/linkQR');
const textQR = require('../models/textQR');
const Session = require('../models/Session');
const jwt = require('jsonwebtoken');

const listQRCodes = async (req, res) => {
    try {
         // Access the token from the session or Session schema
         const tokenID = req.params.id;
            console.log(tokenID);
         const session = await Session.findOne({ _id: tokenID });
         
         console.log(session);

        // Get the JWT token from the session
        const token = session.jwtToken;
            

        //decode the token
        const decoded = await jwt.verify(token, process.env.TOKEN_SECRET);
        // Get the user details from the decoded token
        const id = decoded.id;
    
        currentAccount = id;
        // Retrieve all QR codes generated by the current user
        const personalQRCodes = await personalQR.find({ account: currentAccount });
        const linkQRCodes = await linkQR.find({ account: currentAccount });
        const textQRCodes = await textQR.find({ account: currentAccount });
        // Combine all QR codes into a single array
        const allQRCodes = [...personalQRCodes, ...linkQRCodes, ...textQRCodes];

        // Render the page with the list of QR codes
        res.render('qrList', { qrCodes: allQRCodes, tokenID: tokenID });

    } catch (err) {
        console.error(err);
        res.status(500).send('Internal Server Error');
    }
};

module.exports = {
    listQRCodes,
};
